version: '3.8'


services:
  auth:
    build:
      context: user_service
      dockerfile: Dockerfile
    depends_on:
      - db
    command: /auth/run_test_and_service.sh
    ports:
      - "5000:5000"
    env_file:
      - user_service/.env
  media:
    build:
      context: video_service
      dockerfile: Dockerfile
    depends_on:
      - auth
      - db
    command: /media/run_service.sh
    volumes:
      - static_data:/media/static/
    env_file:
      - video_service/.env
    ports:
      - "5001:5001"
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=anihori
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=anihori_db
volumes:
    postgres_data:
    static_data: