version: '3.8'


services:
  auth:
    build:
      context: user_service
      dockerfile: Dockerfile
    depends_on:
      - db
    command: python3 run.py
    ports:
      - "5000:5000"
    env_file:
      - user_service/.env

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=anihori
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=anihori_db
volumes:
    postgres_data: